# FastAPI stack
fastapi==0.112.2
uvicorn[standard]==0.30.6
python-multipart==0.0.9
pydantic==2.9.2
sqlmodel==0.0.21


# NLP / Search
sentence-transformers==3.0.1
faiss-cpu==1.8.0.post1


# Parsing
pdfplumber==0.11.4
docx2txt==0.8


# Utils
numpy==1.26.4